data_ingestion:
  source:data/raw/spotify-tracks-dataset.csv
  train_ratio: 0.8
  artifact_dir: artifacts/data_ingestion

data_validation:
  schema_file_path: config/schema.yaml

model_trainer:
  model_type: RandomForest

model_pusher:
  export_dir: models/